name: zaihandazi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.3
  http: ^1.5.0
  http_parser: ^4.1.1
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC-VF.ttf
    - family: Noto Sans KR
      fonts:
        - asset: assets/fonts/NotoSansKR-VF.ttf
    - family: Noto Emoji
      fonts:
        - asset: assets/fonts/NotoEmoji-VF.ttf
